server:
  port: 8222
spring:
  application:
    name: service-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: service-edu
          uri: lb://service-edu
          predicates:
            - Path=/eduservice/** # 路径匹配
        - id: service-ucenter
          uri: lb://service-ucenter
          predicates:
            - Path=/ucenter/** # 路径匹配
        - id: service-order
          uri: lb://service-order
          predicates:
            - Path=/eduorder/** # 路径匹配
        - id: service-sta
          uri: lb://service-statistics
          predicates:
            - Path=/staservice/** # 路径匹配
        - id: service-cms
          uri: lb://service-cms
          predicates:
            - Path=/educms/** # 路径匹配
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848